import { Inter } from "next/font/google";
import "./globals.css";
import NewTodoForm from "./NewTodoForm";
import { Metadata } from "next";
import ContextProvider from "./ContextProvider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface StateType {
  todos: string[];
  dones: string[];
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: any;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          {children}
          <Suspense fallback={<></>}>
            <NewTodoForm />
          </Suspense>
          {modal}
        </ContextProvider>
      </body>
    </html>
  );
}
